fast:
	pdflatex abstract

all:
	pdflatex abstract
	pdflatex abstract
	bibtex abstract
	bibtex abstract
	pdflatex abstract
	bibtex abstract
	pdflatex abstract

clean:
	rm -f *.log *.aux *.out *~ *.bbl *.blg
